### ISSUE TITLE
More barcode/qrcode standards needed?

### ISSUE THREAD

**Issue by JanezCZ** [belohoub/UBcards#10]
Czech business chains like Albert or Kaufland have static loyalty cards provided through their apps.
Scanning ends with codes not recognized. Albert has barcode style, Kaufland uses QR code style.

I tried to scan codes with Tagger app:

- Albert barcode did not pass
  - [https://products.aspose.app/barcode/recognize](https://products.aspose.app/barcode/recognize) recognized card as Code-128
- Kaufland QR code successfully read, but cannot be recreated in UBcards or in Tagger (looks different)
  - [https://www.the-qrcode-generator.com](https://www.the-qrcode-generator.com) gives matching output
  - [https://qrgenerator.cz/#text](https://qrgenerator.cz/#text) generates not matching QR code with same input
  - UBcards generates QR code which is completely different from other generated through official app or web pages above

I will try to use the "wrong" codes in near future to determine whether it is needed to modify some generation settings.

**Comment by JanezCZ** [comment]
**Albert loyalty card update**
I tried to use Albert loyalty card barcode today. Self-service checkout terminal did recognize I was presenting loyalty card. But after trying to pair it to an account, terminal reported an error with loyalty card system and did not match the loyalty account correctly.
So at least for this mismatch there would come handy some kind of solution.

*Just to mention - Catima on Android do work with Albert loyalty card system*

**Comment by belohoub** [comment]
Thank you for reporting an issue. The Code-128 generation was completely  copied from the older CardWallet Application and unverified by me :-(. I'll try to test and let you know.

**Comment by belohoub** [comment]
The story with QR codes is completely different. I reviewed the code again, and the root of the problem would be probably this: UBCards (and also Tagger, which uses the same code base for this) automatically selects the minimal needed version of the QR code to represent given data.

The loyalty card could have different settings of QR code version and ECC, but both codes (the original and the application-generated) should be standard-compliant and correct, while the code from UBcards should  be "minimal" with statically pre-defined ECC settings. Simply said, the QR-code is re-generated with different settings than the original code.

I had the same situation with several other loyalty QR codes, and there was never problem (at least CrossCafe and Lidl works) - the reader should usually not care about QR code "settings", only decoded code matters. And when the code is compliant (which is true), it should work.

**Comment by belohoub** [comment]
Dear @JanezCZ ,
thank you for testing!

I also registered the Albert app, and I only used the acpose app to decode. Then, I used UBcards to generate a barcode using the acpose string, and finally, I tried to decode the Ubcards barcode by acpose again. It worked for me, but it is a very incomplete test.

If you will confirm, that it does not work for your case, let's make a deeper investigation.

In any case, changes must be incorporated into Ubcards to properly support these codes without any workarounds.

**Comment by belohoub** [comment]
@JanezCZ I re-investigated it, and I found a small issue in the CODE 128 generation process.

It did not affect some decoders - the generated code was "almost" OK (only the preamble and stop characters were affected).

I also added two new options:
  * if you choose the "PICTURE" barcode type, the picture of the code will be used if available (the crop barcode from the picture taken by the camera ...)
  * if you choose CODE-128-mini, the different encoder for CODE-128 will be used. This encoder can combine multiple CODE-128 subtypes in one code to make the resulting barcode shorter (but sometimes it generates longer code ;-)) I added it as a separate option to not affect existing codes.

Could you test these options with the Albert card?
Could you test currently working CODE-128 cards for possible regressions?
I'll try to do so soon as well.

The release for testing is [0.1.3](https://github.com/belohoub/UBcards/releases/tag/0.1.3)

Thank you!

**Comment by belohoub** [comment]
I did few visits in shops since I implemented the update, and Code-128 I used still work with re-implementation.
My Albert card tested today started work from the UBcards - with Code-128, not with "PICTURE" ;-) - as well.

**Comment by belohoub** [comment]
Fix-release published now.
