### ISSUE TITLE
Xenial build

### ISSUE THREAD

**Issue by Vistaus** [belohoub/UBcards#4]
Thanks for expanding that old app! It was a nice app, but more features were desperatley needed! However, my device is still on Xenial and there's no timeline for a Focal build yet (it should come, as it's not that old of a device yet, but no ETA), so it would be fantastic if you would could add Xenial support! 🙂

**Comment by Vistaus** [comment]
True, but the few features that are added are really useful. Thanks for looking into it - I really appreciate it! 🙂

**Comment by belohoub** [comment]
First try for Xenial: https://github.com/belohoub/UBcards/releases/tag/0.1.1-xenial

Only 64-bit arm for now (due to some dependency issues with the xenial repo, I'm unable to build armhf)

**Comment by Vistaus** [comment]
Thanks! Just installed it, but upon opening, it only shows a blank screen.

**Comment by belohoub** [comment]
Just another regression. I just updated the click, please try again. I'm sorry, I cannot test on real device.
In emulator it looks fine now (at least the part, which could be tested).

**Comment by Vistaus** [comment]
> Just another regression. I just updated the click, please try again. I'm sorry, I cannot test on real device.

No problem, that's what testing is for, right? :D

In emulator it looks fine now (at least the part, which could be tested).

The new build works! Or at least until the add screen. Will add my cards from Card Wallet later, but looking promising so far!

**Comment by Vistaus** [comment]
Hmm, I just tried to add one of my cards and I got very far, but on the last screen, there's no way to input the card number…

**Comment by belohoub** [comment]
You can input card number only on the first screen (pulled from the bottom edge), by scanning code or from the photo, then it is not possible to edit it. Only type or category could be edited on the edit page.

**Comment by belohoub** [comment]
Yes, it is. What you suggest?

Could you please try decoding BarCode from picture or by phone camera? Another user reported it does not work on Xenial ...

**Comment by Vistaus** [comment]
I think Card Number would be a good and clear name.

As for decoding:

* Decoding from a photo from the gallery works;
* Decoding using the camera/scanner from within UBcards doesn't work. I think the issue is that focus doesn't work.

**Comment by belohoub** [comment]
OK. Thank you

Thank you for testing. I'll have a look at this to find out if it is possible some simple tuning. This is a component I took untouched from Tagger application, while there is just "some" autofocus.

**Comment by belohoub** [comment]
@Vistaus Could you test updated files: https://github.com/belohoub/UBcards/releases/tag/0.1.1-xenial ?
I changed autofocus to focusing on center in camera settings - it could help on your device ...

**Comment by Vistaus** [comment]
Just tried the new build and it is more focused than in the previous build, but it still doesn't autofocus. And despite being more focused, it still doesn't read the barcodes I tried.

Btw, not sure if it makes any difference, but just to give you as much information as possible: the barcodes I'm trying are EAN-13.

**Comment by belohoub** [comment]
Thank you!
The code type *should* be irrelevant.  Just to clarify - if you make a photo of the barcode using your camera and parse it from the image - that worked?

It seems to me, that autofocus might be broken on some devices. I'll need some time to implement manual focus, which enterprisingly helps a lot on my device in the camera app ...

**Comment by belohoub** [comment]
Release has been published at open-store.

**Comment by Vistaus** [comment]
Awesome! Thank you so much! 🙂
